language: java

matrix:
  include:
    - name: Ubuntu 14.04 JDK 9
      os: linux
      jdk: oraclejdk9

    - name: macOS
      os: osx
      osx_image: xcode10.1

script:
  - ./config/travis/run-checks.sh
  - npm run lint frontend/src/**/*.js
  - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest

before_install:
  - npm install --only=dev

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
