language: java

matrix:
  include:
    - name: Ubuntu 14.04 JDK 8
      os: linux
      jdk: openjdk8
      before_install:
        - sudo apt-get update
        - sudo apt-get --only-upgrade install openjdk-8-jdk
        - echo -e "Actual JDK in use -- "; java -version

    - name: macOS 10.13.6 JDK 8
      os: osx
      osx_image: xcode10.1
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1 # Prevent time-consuming brew update
      before_install:
        - *common_before_install
        - brew install cask
        - brew cask install AdoptOpenJDK/openjdk/adoptopenjdk8
        - export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
        - echo -e "Actual JDK in use -- "; java -version

    - name: "Cypress frontend tests"
      os: linux
      dist: xenial
      addons:
        chrome: stable
      services:
        - xvfb
      before_install:
        - *common_before_install
        - sudo apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      script:
        - ./gradlew frontendTest -Pci

script:
  - ./config/travis/run-checks.sh
  - npm run lint
  - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest coverage

before_install: &common_before_install
  - npm install --only=dev

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  npm: true,
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cache

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - |
    if [ "$TRAVIS_JOB_NAME" = "Ubuntu 14.04 JDK 8" ];
    then
      git fetch --all && git config --global user.email "-" && git config --global user.name "-" && ./gradlew run -Dargs="--since d1"
      npm install -g surge
      ./config/travis/deploy-surge.sh
    fi
