# AppVeyor configuration file
# For more details see https://www.appveyor.com/docs/build-configuration/

image:
  - Visual Studio 2015
  - Previous Visual Studio 2015

# Call on gradle to build and run tests
# --no-daemon: Prevent the daemon from launching to prevent file-in-use errors
#     when we cache the ~/.gradle directory
build_script:
    - gradlew.bat --no-daemon clean checkstyleMain checkstyleTest

test_script:
    - appveyor-retry gradlew.bat --no-daemon test systemTest

environment:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0  # Use 64-bit Java

# Files/folders to preserve between builds to speed them up
cache:
    - C:\Users\appveyor\.gradle
